"""Generate bounded bitmap/catalog data. Usage: python tools/build_languages.py [font.hex.gz jp.hex.gz]
Without arguments uses the checked-in glyph subset. Unifont 16.0.04, OFL-1.1.
"""
from pathlib import Path
import gzip,json,sys
root=Path(__file__).resolve().parents[1];a=root/'assets/languages'
rows=[x.split('|') for x in (a/'catalog.tsv').read_text().splitlines() if x]
assert all(len(r)==7 for r in rows)
chars=set(''.join(''.join(r) for r in rows))|set('English Español Français Deutsch 日本語 简体中文 עברית')|set(chr(i) for i in range(32,127))
if len(sys.argv)==3:
 fonts=[]
 for name in sys.argv[1:]:
  fonts.append({int(l.split(':')[0],16):l.split(':')[1] for l in gzip.open(name,'rt').read().splitlines()})
 subset={str(ord(c)):[fonts[0][ord(c)],fonts[1][ord(c)]] for c in sorted(chars)}
 (a/'glyphs.json').write_text(json.dumps(subset,ensure_ascii=False))
else:subset=json.loads((a/'glyphs.json').read_text())
q=lambda x:json.dumps(x,ensure_ascii=False)
s='// Generated by tools/build_languages.py. Glyphs: Unifont 16.0.04, OFL-1.1.\n'
s+='static const char* const catalog[][7]={\n'+',\n'.join('{'+','.join(q(x) for x in r)+'}' for r in sorted(rows))+'\n};\n'
def encode(bits):
 stride=len(bits)//16;previous=bytes(stride);mask=0;data=bytearray()
 for r in range(16):
  row=bits[r*stride:(r+1)*stride]
  if row!=previous:mask|=1<<r;data.extend(row)
  previous=row
 return mask.to_bytes(2,'little')+data

def decode(data,stride):
 mask=int.from_bytes(data[:2],'little');pos=2;previous=bytes(stride);out=bytearray()
 for r in range(16):
  if mask&(1<<r):previous=data[pos:pos+stride];pos+=stride
  out.extend(previous)
 assert pos==len(data)
 return out

blob=bytearray(); offsets={}; glyphrows=[]
for key,pair in sorted(subset.items(),key=lambda x:int(x[0])):
 assert chr(int(key)) in chars
 b=[bytes.fromhex(v) for v in pair];assert len(b[0]) in (16,32) and len(b[1])==len(b[0])
 ids=[]
 for bits in b:
  if bits not in offsets:offsets[bits]=len(blob);blob.extend(encode(bits))
  ids.append(offsets[bits])
 # Verify every normal/Japanese glyph survives deduplication byte-for-byte.
 for bits,offset in zip(b,ids):assert decode(encode(bits),len(bits)//16)==bits
 glyphrows.append('{'+f'{key},{ids[0]},{ids[1]},{len(b[0])//2}'+'}')
assert len(blob)<65536
s+='struct Glyph{uint16_t cp,offset,jpOffset;uint8_t width;};\nstatic const Glyph glyphs[]={\n'+',\n'.join(glyphrows)+'\n};\n'
s+='static const uint8_t glyphBits[]={\n'+','.join(str(x) for x in blob)+'\n};\n'
(root/'include/language_data.h').write_text(s)
print(len(rows),'translations;',len(subset),'glyphs;',len(blob),'shared bitmap bytes')
