#!/usr/bin/env python3
"""Pack the printable installation guide into the firmware's tiny LZ stream."""
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
src = (ROOT / "DNSQUACHWATCH INSTALLATION.txt").read_bytes()
out = bytearray()
i = 0
# Two-byte matches carry a 10-bit backward distance and six-bit length.
# This bounds decoder history to 1 KiB and match length to 66 bytes.
while i < len(src):
    flag_at = len(out)
    out.append(0)
    flags = 0
    for bit in range(8):
        if i >= len(src):
            break
        best_len = 0
        best_off = 0
        for off in range(1, min(1024, i) + 1):
            length = 0
            while length < 66 and i + length < len(src) and src[i + length] == src[i + length - off]:
                length += 1
            if length > best_len:
                best_len, best_off = length, off
        if best_len >= 3:
            flags |= 1 << bit
            packed = ((best_off - 1) << 6) | (best_len - 3)
            out.extend((packed & 0xFF, packed >> 8))
            i += best_len
        else:
            out.append(src[i])
            i += 1
    out[flag_at] = flags

lines = ["// Generated by tools/pack_installation_guide.py; do not edit by hand.",
         f"static const uint8_t PACKED[{len(out)}] = {{"]
for at in range(0, len(out), 16):
    lines.append("    " + ", ".join(f"0x{x:02x}" for x in out[at:at+16]) + ",")
lines += ["};", f"static const size_t PACKED_SIZE = {len(out)};", f"static const size_t UNPACKED_SIZE = {len(src)};"]
(ROOT / "include/installation_guide_data.inc").write_text("\n".join(lines) + "\n")
print(f"{len(src)} -> {len(out)} bytes ({100*len(out)/len(src):.1f}%)")
